version: '2'
services:
  db:
    restart: always
    image: postgres
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    ports:
      - '15432:5432'
    environment:
      POSTGRES_DB: devcon
  laravel:
    build:
      context: ./docker/php
    restart: always
    volumes:
      - ./laravel:/var/www/html
    depends_on:
      - db
  rails:
    build:
      context: ./docker/rails
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    restart: always
    volumes:
      - ./rails:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  django:
    build:
      context: ./django
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django:/code
    ports:
      - "8000:8000"
    depends_on:
      - db